### ISSUE TITLE
Improve preprocessing component

### ISSUE THREAD

**Issue by jordiplanascuchi** [wri-dssg-omdena/policy-data-analyzer#48]
The current method that we are using to split sentences yields a great amount of wrongly splitt sentences.
We need to improve it so as to have a good final version when we want to use the fine-tunned transformers.

**Comment by jordiplanascuchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split into sentences improvement](https://trello.com/c/xPSOHaMK/77-split-into-sentences-improvement)

**Comment by thefirebanks** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polish preprocessing code](https://trello.com/c/Jj87gK8r/85-polish-preprocessing-code)

**Comment by thefirebanks** [comment]
Steps:
- [ ] Sentence splitting pt. 1, experiment with external libraries (try multilingual if possible)
- [ ] Sentence splitting pt. 2, compare with current sentence splitting script and choose one
- [ ] Build input pipeline as a script pt. 1, import documents as text from Amazon S3 bucket
- [ ] Build input pipeline as a script pt. 2, join OCR and other components of input pipeline together
- [ ] Build output pipeline as a script, sentences ready for assisted labeling component
- [ ] _**Bonus if time:**_ Make it an API

**Comment by thefirebanks** [comment]
- [ ] Add rules for Mexico
- [ ] Add rules for El Salvador
- [ ] Add rules for Chile
